name = "worker-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

kv_namespaces = [
  { binding = "RUST_CHESS_V1", id = "6d7b63da622e4739a0c7f33a4643de68" }
]

[build]
command = "cargo install -q worker-build && worker-build --release"
